# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chariot < Formula
  desc "Deploy and manage enterprise agent fleets from your terminal"
  homepage "https://app.chariots.sh"
  version "0.1.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chariots-sh/Chariot-CLI/releases/download/v0.1.15/chariot_0.1.15_darwin_amd64.tar.gz"
      sha256 "69df254780c631e01fa66a76b2d7d7155cd453d5c14137fdbb1a5f681675c732"

      define_method(:install) do
        bin.install "chariot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chariots-sh/Chariot-CLI/releases/download/v0.1.15/chariot_0.1.15_darwin_arm64.tar.gz"
      sha256 "cf90de4243bdb58eb8dfc2e1ba3aa956d291c2a9de3deb844639440b4d49602d"

      define_method(:install) do
        bin.install "chariot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chariots-sh/Chariot-CLI/releases/download/v0.1.15/chariot_0.1.15_linux_amd64.tar.gz"
      sha256 "d147e36462094d6397ff7cc13281468b9a4ff11ab182255b085d95f553a2618f"
      define_method(:install) do
        bin.install "chariot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chariots-sh/Chariot-CLI/releases/download/v0.1.15/chariot_0.1.15_linux_arm64.tar.gz"
      sha256 "42e2a000799d457fc38d8d56f88803725db9af3015d2628096b220ac853c7aaf"
      define_method(:install) do
        bin.install "chariot"
      end
    end
  end

  test do
    system "#{bin}/chariot", "version"
  end
end
